### ISSUE TITLE
ircretary tell <person1> and <person2> something

### ISSUE THREAD

**Issue by japj** [isaacs/ircretary#2]
I just noted this:

12:41:04    <saghul>    ircretary tell bnoordhuis and piscisauseus that they rock :-)
12:41:05    <ircretary> saghul: I'll be sure to tell bnoordhuis
12:41:10    <saghul>    ircretary thanks
12:41:10    <ircretary> saghul: You're welcome :)

unfortunately there was also a spelling error in piscisaureus, but it seems he would not have gotten the message even if it was spelled correctly?.

**Comment by isaacs** [comment]
True, messages are only for one person.

This would be a nice addition.  Patch welcome.
